#mysql database connection
spring.application.name=SpringBootCore_Project07_LayeredApp_MinPrj_OracleAndMySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/spbootcore?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tanmay
dao.id = empMySQLService


#Oracle database Connection
#spring.application.name=SpringBootCore_Project07_LayeredApp_MinPrj_OracleAndMySQL
#spring.datasource.driver-class-name= oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.datasource.username=tanmay
#spring.datasource.password=tanmay
#dao.id = empOracleService
