#Presentation labels (English) base file
# {0} we are using this for getting the additional values for the properties
welcome.msg= Good Morning {0} 
goodbye.msg = see you soon {0}
wish.msg = Happy new year {0}
# note = All these files must have propeties as the extention...
# note = All these properties file must have same keys and different values
