#Data source configuration 
#Here we are setting properties with jdbc 
#driver,url,username and password 
#by this approach we can change data base as per our requirements in future
spring.application.name=SpringBootCore_Project06_LayeredApp_MinPrj
spring.datasource.driver-class-name= oracle.jdbc.driver.OracleDriver
spring.datasource.url= jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=tanmay
spring.datasource.password=tanmay